# Generated by Django 4.1.7 on 2024-06-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='image'),
        ),
    ]
