# Generated by Django 4.1.7 on 2024-06-24 07:42

import uuid

import django.db.models.deletion
from django.db import migrations, models

import hotel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_hotel_image_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=hotel_app.models.get_datetime, null=True, validators=[hotel_app.models.check_created], verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, validators=[hotel_app.models.check_modified], verbose_name='modified')),
                ('city', models.TextField(max_length=250)),
                ('street', models.TextField(max_length=250)),
                ('number', models.IntegerField(validators=[hotel_app.models.check_positive])),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
                'db_table': '"hotel"."address"',
            },
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.address', verbose_name='address'),
        ),
    ]
